### ISSUE TITLE
Return native promise support

### ISSUE THREAD

**Issue by jeetiss** [tradable/tradable-core#5]
Please return native promise support or use A+ promises.

**Comment by oizulain** [comment]
Hi @jeetiss, we don't use native Promises because they are not supported by all browsers ([see support](http://caniuse.com/#feat=promises)). Since we require jQuery, we use jQuery promises. Now, whether the jQuery promises are A+ conformant or not depends on the jQuery version you use. For the jQuery promises to be [A+ conformant](https://promisesaplus.com/implementations) you need to use [jQuery 3.0 or newer](https://api.jquery.com/category/deferred-object/). If you encounter any issues using jQuery 3.0 please let us know.
